import javax.swing.*;
import java.awt.event.*;

public class Addition{
    public static void main(String[] args){
        JFrame frame = new JFrame("Addition of Two numbers");
        JLabel label1 = new JLabel("Enter 1st Number : ");
        JLabel label2 = new JLabel("Enter 2nd Number : ");
        Jlabel answer = new JLabel("Result : ");

        JTextField text1 = new JTextField(10);
        JTextField text2 = new JTextField(10);
        JTextField result = new JTextField(10);
        result.setEditable(False);

        JButton addbutton = new JButton("Add");

        label1.setBounds(center);
        text1.setBounds(center);
    }
}